<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36069" started-at="2018-08-04T18:31:36Z" finished-at="2018-08-04T18:32:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36069" started-at="2018-08-04T18:31:36Z" finished-at="2018-08-04T18:32:12Z">
      <class name="com.qtpselenium.hybrid.suitea.LoginTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="init" is-config="true" duration-ms="681" started-at="2018-08-05T00:01:36Z" finished-at="2018-08-05T00:01:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="initTest" is-config="true" duration-ms="199" started-at="2018-08-05T00:01:37Z" finished-at="2018-08-05T00:01:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="FAIL" signature="logintest(java.util.Hashtable)[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="logintest" duration-ms="31980" started-at="2018-08-05T00:01:37Z" data-provider="getData" finished-at="2018-08-05T00:02:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=U1, ExpectedResult=LoginSuccess, Password=P1, Runmode=Y, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.qtpselenium.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:54)
	at com.qtpselenium.hybrid.suitea.LoginTest.logintest(LoginTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
	Titles did not match. Got title as Zoho - Cloud Software Suite and SaaS Applications for Businesses,
	Object Not Found signinLink_xpath
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.qtpselenium.keywords.GenericKeywords.reportFailure(GenericKeywords.java:221)
	at com.qtpselenium.keywords.GenericKeywords.getObject(GenericKeywords.java:182)
	at com.qtpselenium.keywords.GenericKeywords.click(GenericKeywords.java:120)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="quit" is-config="true" duration-ms="2972" started-at="2018-08-05T00:02:09Z" finished-at="2018-08-05T00:02:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="initTest" is-config="true" duration-ms="0" started-at="2018-08-05T00:02:12Z" finished-at="2018-08-05T00:02:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="SKIP" signature="logintest(java.util.Hashtable)[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="logintest" duration-ms="4" started-at="2018-08-05T00:02:12Z" data-provider="getData" finished-at="2018-08-05T00:02:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=itsthaku.r@gmail.com, ExpectedResult=LoginSuccess, Password=Ashish@123, Runmode=N, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode is set to NO
	at com.qtpselenium.hybrid.suitea.LoginTest.logintest(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="quit" is-config="true" duration-ms="99" started-at="2018-08-05T00:02:12Z" finished-at="2018-08-05T00:02:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="initTest" is-config="true" duration-ms="1" started-at="2018-08-05T00:02:12Z" finished-at="2018-08-05T00:02:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="SKIP" signature="logintest(java.util.Hashtable)[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="logintest" duration-ms="2" started-at="2018-08-05T00:02:12Z" data-provider="getData" finished-at="2018-08-05T00:02:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=U3, ExpectedResult=LoginFailure, Password=P3, Runmode=N, Browser=Edge}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Runmode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Runmode is set to NO
	at com.qtpselenium.hybrid.suitea.LoginTest.logintest(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.qtpselenium.hybrid.suitea.LoginTest@d8355a8]" name="quit" is-config="true" duration-ms="74" started-at="2018-08-05T00:02:12Z" finished-at="2018-08-05T00:02:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.qtpselenium.hybrid.suitea.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
